build: false

os: Visual Studio 2015

platform:
  - x64
  - x86

environment:
  MINICONDA: C:\Miniconda
  matrix:
    - COLUMN_MAJOR_LAYOUT: OFF
    - COLUMN_MAJOR_LAYOUT: ON

matrix:
  fast_finish: true
  allow_failures:
    - COLUMN_MAJOR_LAYOUT: ON

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda install cmake xtensor
  - mkdir C:\fftw_download
  - ps: if($env:Platform -eq "x86"){$source = "ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll32.zip"; $destination = "C:\fftw-3.3.5.zip"; Invoke-WebRequest $source -OutFile $destination; echo "x86 fftw download complete"}
  - ps: if($env:Platform -eq "x64"){$source = "ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll64.zip"; $destination = "C:\fftw-3.3.5.zip"; Invoke-WebRequest $source -OutFile $destination; echo "x64 fftw download complete"}
  - 7z e C:\fftw-3.3.5.zip -oC:\fftw_download
  - cd C:\fftw_download
  - ps: if($env:Platform -eq "x86"){lib.exe /def:libfftw3-3.def; lib.exe /def:libfftw3f-3.def; lib.exe /def:libfftw3l-3.def}
  - ps: if($env:Platform -eq "x64"){lib.exe /machine:x64 /def:libfftw3-3.def; lib.exe /machine:x64 /def:libfftw3f-3.def; lib.exe /machine:x64 /def:libfftw3l-3.def}
  - dir
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DFFTW_ROOT="C:\fftw_download" -DCMAKE_INSTALL_PREFIX=%MINICONDA%\\LIBRARY -DBUILD_TESTS=ON -DDEFAULT_COLUMN_MAJOR=%COLUMN_MAJOR_LAYOUT% -DDOWNLOAD_GTEST=ON ..
  - nmake test_xtensor-fftw
  - cd test

build_script:
  - test_xtensor-fftw.exe
