language: cpp
addons:
  apt:
    packages:
matrix:
  include:
    # code coverage:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libfftw3-dev
            - lcov
      env: COMPILER=gcc GCC=7 COVERAGE=ON
    # normal tests:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libfftw3-dev
      env: COMPILER=gcc GCC=4.9
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libfftw3-dev
      env: COMPILER=gcc GCC=5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libfftw3-dev
      env: COMPILER=gcc GCC=6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libfftw3-dev
      env: COMPILER=gcc GCC=7
    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libfftw3-dev
      env: COMPILER=clang CLANG=3.6
    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libfftw3-dev
      env: COMPILER=clang CLANG=3.7
    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - libfftw3-dev
      env: COMPILER=clang CLANG=3.8
    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
            - libfftw3-dev
      env: COMPILER=clang CLANG=3.9
    - os: osx
      osx_image: xcode8
      compiler: clang
    - os: osx
      osx_image: xcode8.3
      compiler: clang

env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
before_install:
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$COMPILER" == "gcc" ]]; then
          export CXX=g++-$GCC CC=gcc-$GCC;
        fi
        if [[ "$COMPILER" == "clang" ]]; then
          export CXX=clang++-$CLANG CC=clang-$CLANG;
        fi
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CXX=clang++ CC=clang;
      fi
install:
    # Define the version of miniconda to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda update -yq conda
    - |
      # install deps with conda: cmake, gtest, xtensor (and fftw on osx); if conda-forge fails, use xtensor from source
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        conda install -y gtest cmake xtensor fftw -c conda-forge
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if ! conda install -y gtest cmake xtensor -c conda-forge; then
          echo "conda-forge install failed! Installing gtest and cmake from default conda channel."
          conda install -y gtest cmake
          echo "Installing xtensor from source"
          cd $TRAVIS_HOME
          git clone https://github.com/QuantStack/xtensor.git
          cd xtensor
          cmake . -DCMAKE_INSTALL_PREFIX=$HOME/miniconda
          make install
          cd $TRAVIS_BUILD_DIR
        fi
      fi
    # Testing
    - mkdir $TRAVIS_BUILD_DIR/build
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -DBUILD_TESTS=ON -DCOVERAGE=$COVERAGE ..
    - make -j2 test_xtensor-fftw VERBOSE=1
    - if [[ "$COVERAGE" == "ON" ]]; then gem install coveralls-lcov; fi
script:
    - cd test
    - ./test_xtensor-fftw

after_success:
- |
  if [[ "${COVERAGE}" == "ON" ]]; then
    cd ${TRAVIS_BUILD_DIR}/build
    ls
    ls test
    lcov --directory . --capture --output-file coverage.info # capture coverage info
    lcov --remove coverage.info 'tests/*' '/usr/*' 'miniconda/*' --output-file coverage.info # filter out system and test code and external includes
    lcov --list coverage.info # debug before upload
    coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
  fi
