name: xtensor-fftw
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xtensor=0.15.9
  - xtensor-io
  - xeus-cling=0.3.0
  - xtensor-fftw >= 0.2.3
  - notebook
  - widgetsnbextension
  - nbstripout
